import type { NormalizedRecall } from "@/domain/types";
import type { RecallProvider } from "./recall-provider";

const d = (value: string) => new Date(`${value}T12:00:00.000Z`);

export const fixtureRecalls: NormalizedRecall[] = [
  { externalId: "DEMO-FDA-001", sourceAuthority: "FDA", headline: "Demo notice: Romaine salad kits", description: "Fixture notice for selected romaine salad kits due to a possible contamination concern.", brand: "Green Valley", productName: "Romaine Lettuce Salad Kit", category: "Packaged Produce", upcs: ["041234567890"], lotNumbers: ["RV2409A"], distributionStartDate: d("2026-08-20"), distributionEndDate: d("2026-09-12"), recallDate: d("2026-09-13"), severity: "Class I-style demo", recommendedAction: "Do not consume the product. Check the official notice and return it to the place of purchase or discard it.", sourceUrl: "https://www.fda.gov/safety/recalls-market-withdrawals-safety-alerts", isFixture: true },
  { externalId: "DEMO-FDA-002", sourceAuthority: "FDA", headline: "Demo notice: Large brown eggs", description: "Fixture notice for selected cartons of large brown eggs due to potential Salmonella contamination.", brand: "Morning Meadow", productName: "Large Brown Eggs Grade A", category: "Dairy & Eggs", upcs: ["072345678901"], lotNumbers: ["P2146"], distributionStartDate: d("2026-08-15"), distributionEndDate: d("2026-09-08"), recallDate: d("2026-09-10"), severity: "Class I-style demo", recommendedAction: "Do not eat the identified eggs. Return them for a refund or discard them after reviewing the official notice.", sourceUrl: "https://www.fda.gov/safety/recalls-market-withdrawals-safety-alerts", isFixture: true },
  { externalId: "DEMO-CPSC-003", sourceAuthority: "CPSC", headline: "Demo notice: Compact power banks", description: "Fixture notice for selected compact USB-C power banks that may overheat.", brand: "VoltNest", productName: "PocketCharge 10000 Power Bank", category: "Electronics", upcs: ["083456789012"], lotNumbers: ["VN26Q2"], distributionStartDate: d("2026-05-01"), distributionEndDate: d("2026-08-31"), recallDate: d("2026-09-04"), severity: "Fire hazard-style demo", recommendedAction: "Stop using the affected unit and follow the manufacturer's official return instructions.", sourceUrl: "https://www.cpsc.gov/Recalls", isFixture: true },
  { externalId: "DEMO-CPSC-004", sourceAuthority: "CPSC", headline: "Demo notice: Cordless stick vacuums", description: "Fixture notice for a battery enclosure issue in selected cordless vacuums.", brand: "BrightHome", productName: "AirSweep Cordless Stick Vacuum", category: "Household", upcs: ["094567890123"], lotNumbers: ["AS-118"], distributionStartDate: d("2026-01-01"), distributionEndDate: d("2026-07-30"), recallDate: d("2026-08-18"), severity: "Burn hazard-style demo", recommendedAction: "Stop charging the unit and consult the official recall portal for remedy details.", sourceUrl: "https://www.cpsc.gov/Recalls", isFixture: true },
  { externalId: "DEMO-FDA-005", sourceAuthority: "FDA", headline: "Demo notice: Creamy peanut butter", description: "Fixture notice for selected jars because of a possible undeclared allergen.", brand: "Pantry Oak", productName: "Creamy Peanut Butter", category: "Pantry", upcs: ["015678901234"], lotNumbers: ["PB77K"], distributionStartDate: d("2026-06-01"), distributionEndDate: d("2026-08-15"), recallDate: d("2026-08-21"), severity: "Allergen alert-style demo", recommendedAction: "People with the identified allergy should not consume the product; review official guidance for returns.", sourceUrl: "https://www.fda.gov/safety/recalls-market-withdrawals-safety-alerts", isFixture: true },
  { externalId: "DEMO-FDA-006", sourceAuthority: "FDA", headline: "Demo notice: Frozen berry blend", description: "Fixture notice for selected frozen berry bags due to a possible contamination concern.", brand: "North Orchard", productName: "Triple Berry Frozen Fruit Blend", category: "Frozen", upcs: ["026789012345"], lotNumbers: ["FB903"], distributionStartDate: d("2026-04-10"), distributionEndDate: d("2026-07-15"), recallDate: d("2026-07-22"), severity: "Class II-style demo", recommendedAction: "Check the package identifiers and discard or return affected bags.", sourceUrl: "https://www.fda.gov/safety/recalls-market-withdrawals-safety-alerts", isFixture: true },
  { externalId: "DEMO-CPSC-007", sourceAuthority: "CPSC", headline: "Demo notice: Children's night lights", description: "Fixture notice for plug-in night lights with an overheating risk.", brand: "Little Beacon", productName: "Moon Glow Plug-In Night Light", category: "Household", upcs: ["037890123456"], lotNumbers: ["MG44"], distributionStartDate: d("2025-11-01"), distributionEndDate: d("2026-06-30"), recallDate: d("2026-07-08"), severity: "Fire hazard-style demo", recommendedAction: "Unplug the affected night light and review the official recall instructions.", sourceUrl: "https://www.cpsc.gov/Recalls", isFixture: true },
  { externalId: "DEMO-CPSC-008", sourceAuthority: "CPSC", headline: "Demo notice: Insulated travel mugs", description: "Fixture notice for lids that may eject hot liquid under pressure.", brand: "Trail Cup", productName: "Stainless Insulated Travel Mug", category: "Kitchen", upcs: ["048901234567"], lotNumbers: ["TC610"], distributionStartDate: d("2026-02-01"), distributionEndDate: d("2026-07-31"), recallDate: d("2026-08-09"), severity: "Burn hazard-style demo", recommendedAction: "Stop using the affected lid and follow the official remedy instructions.", sourceUrl: "https://www.cpsc.gov/Recalls", isFixture: true },
  { externalId: "DEMO-FDA-009", sourceAuthority: "FDA", headline: "Demo notice: Chicken noodle soup", description: "Fixture notice for cans that may contain an undeclared ingredient.", brand: "Hearth Table", productName: "Classic Chicken Noodle Soup", category: "Pantry", upcs: ["059012345678"], lotNumbers: ["CN810"], distributionStartDate: d("2026-05-01"), distributionEndDate: d("2026-08-01"), recallDate: d("2026-08-14"), severity: "Allergen alert-style demo", recommendedAction: "Review the product label and official notice, then return or discard affected cans.", sourceUrl: "https://www.fda.gov/safety/recalls-market-withdrawals-safety-alerts", isFixture: true },
  { externalId: "DEMO-CPSC-010", sourceAuthority: "CPSC", headline: "Demo notice: Folding step stools", description: "Fixture notice for a hinge that may fail during use.", brand: "Home Harbor", productName: "Two-Step Folding Stool", category: "Household", upcs: ["060123456789"], lotNumbers: ["HH220"], distributionStartDate: d("2025-10-01"), distributionEndDate: d("2026-06-15"), recallDate: d("2026-06-28"), severity: "Fall hazard-style demo", recommendedAction: "Stop using affected stools and consult the official recall portal for the remedy.", sourceUrl: "https://www.cpsc.gov/Recalls", isFixture: true },
];

export class FixtureRecallProvider implements RecallProvider {
  readonly name = "demo-fixtures";
  async fetchRecalls() { return fixtureRecalls; }
}
