-- Additive schema generated by Prisma; applied through its existing migration history.
BEGIN;
ALTER TABLE "AppUser"
  ADD COLUMN "emailAlertsConsentedAt" TIMESTAMP(3),
  ADD COLUMN "emailAlertsEnabled" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN "notificationEmail" TEXT,
  ADD COLUMN "unsubscribeToken" TEXT;
CREATE TABLE "EmailNotification" (
  "id" TEXT NOT NULL,
  "dedupeKey" TEXT NOT NULL,
  "userId" TEXT NOT NULL,
  "matchId" TEXT,
  "status" TEXT NOT NULL DEFAULT 'PENDING',
  "attempts" INTEGER NOT NULL DEFAULT 0,
  "nextAttemptAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "firstAttemptAt" TIMESTAMP(3),
  "lockedAt" TIMESTAMP(3),
  "sentAt" TIMESTAMP(3),
  "providerMessageId" TEXT,
  "lastError" TEXT,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "EmailNotification_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "EmailNotification_dedupeKey_key" ON "EmailNotification"("dedupeKey");
CREATE INDEX "EmailNotification_status_nextAttemptAt_idx" ON "EmailNotification"("status", "nextAttemptAt");
CREATE INDEX "EmailNotification_userId_idx" ON "EmailNotification"("userId");
CREATE INDEX "EmailNotification_matchId_idx" ON "EmailNotification"("matchId");
CREATE UNIQUE INDEX "AppUser_unsubscribeToken_key" ON "AppUser"("unsubscribeToken");
CREATE INDEX "RecallMatch_recallId_idx" ON "RecallMatch"("recallId");
ALTER TABLE "EmailNotification" ADD CONSTRAINT "EmailNotification_userId_fkey" FOREIGN KEY ("userId") REFERENCES "AppUser"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "EmailNotification" ADD CONSTRAINT "EmailNotification_matchId_fkey" FOREIGN KEY ("matchId") REFERENCES "RecallMatch"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "EmailNotification" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON "EmailNotification" FROM PUBLIC;
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'anon') THEN
    REVOKE ALL ON "EmailNotification" FROM anon;
  END IF;
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'authenticated') THEN
    REVOKE ALL ON "EmailNotification" FROM authenticated;
  END IF;
END $$;
COMMIT;
